version: '3.8'

services:
  postgres:
    env_file: .env
    container_name: postgres
    build: ./postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data_volume:/var/lib/postgresql/data
    networks:
      - my_net
  app:
    env_file: .env
    container_name: app
    image: image-app
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    depends_on:
      - postgres
    restart: always
    volumes:
      - data_volume:/var/lib/postgresql/data
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
volumes:
  data_volume:
