version: '3.8'

services:
  db:
    env_file: .env
    container_name: ${APP_NAME}_db
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5434:5432
    restart: on-failure
    volumes:
      - data_volume:/data
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
volumes:
  data_volume:
