version: '3.8'

services:
  postgres:
    env_file: .env
    container_name: postgres
    # image: image-postgres
    build: ./postgres
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - data_volume:/data
    networks:
      - my_net
  app:
    env_file: .env
    container_name: app
    image: image-app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - data_volume:/data
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
volumes:
  data_volume:
